name: prerelease
on:
    push:
        branches:
            - master

jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '16.x'
                registry-url: 'https://registry.npmjs.org'
            - run: |
                npm ci
                npm run build

            - uses: actions/github-script@v6
              with:
                script: |
                    const packageFile = "./package.json";
                    const pkg = JSON.parse((await fs.readFile(packageFile)).toString());
                    pkg.version = `${pkg.version}-next`;
                    await fs.writeFile(packageFile, JSON.stringify(pkg, null, "    "));
                    console.log("Prerelease version: " + pkg.version);

            - run: npm publish dist --tag next
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}