name: prerelease
on:
    push:
        branches:
            - master

jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Make prerelease to npm
              uses: epeli/npm-release@v1
              with:
                  type: prerelease
                  token: ${{ secrets.NPM_TOKEN }}
            - name: test coverage
              run: |
                npm test -- --coverage
                bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}